---

# For use with pre-commit.
# See usage instructions at http://pre-commit.com

-   id: gflows
    name: Gflows
    description: This hook runs gflows check to ensure updates to ytt templates are reflected in github workflows.
    entry: gflows check
    language: system
